GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/681be07344c1fbeed019b447

###
DELETE http://localhost:3001/api/persons/681cfe1cadadadada67198f1b9fc66ef1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ge",
    "number": "12345"
}

###
PUT http://localhost:3001/api/persons/681be07344c1fbeed019b447
Content-Type: application/json

{
    "number": "12345"
}
